// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_tasks.sql

package queries

import (
	"context"
)

const claimJobTask = `-- name: ClaimJobTask :one
WITH next_task AS (
  SELECT id
  FROM job_tasks
  WHERE status = 'pending'
  ORDER BY created_at
  LIMIT 1
  FOR UPDATE SKIP LOCKED
), claimed AS (
  UPDATE job_tasks t
  SET
    status = 'running',
    updated_at = now()
  FROM next_task
  WHERE t.id = next_task.id
  RETURNING t.id, t.job_id, t.rendition_id, t.status, t.error_message, t.created_at, t.updated_at
)
SELECT
  c.id AS task_id,
  c.job_id,
  c.rendition_id,
  j.source_path,
  j.output_dir,
  j.file_name,
  p.hls_segment_time,
  r.name AS rendition_name,
  r.width,
  r.height,
  r.video_bitrate,
  r.audio_bitrate,
  r.video_codec,
  r.audio_codec
FROM claimed c
JOIN jobs j ON j.id = c.job_id
JOIN renditions r ON r.id = c.rendition_id
JOIN transcode_profiles p ON p.id = j.profile_id
`

type ClaimJobTaskRow struct {
	TaskID         int64
	JobID          int64
	RenditionID    int64
	SourcePath     string
	OutputDir      string
	FileName       string
	HlsSegmentTime int32
	RenditionName  string
	Width          int32
	Height         int32
	VideoBitrate   int32
	AudioBitrate   int32
	VideoCodec     string
	AudioCodec     string
}

func (q *Queries) ClaimJobTask(ctx context.Context) (ClaimJobTaskRow, error) {
	row := q.db.QueryRow(ctx, claimJobTask)
	var i ClaimJobTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.JobID,
		&i.RenditionID,
		&i.SourcePath,
		&i.OutputDir,
		&i.FileName,
		&i.HlsSegmentTime,
		&i.RenditionName,
		&i.Width,
		&i.Height,
		&i.VideoBitrate,
		&i.AudioBitrate,
		&i.VideoCodec,
		&i.AudioCodec,
	)
	return i, err
}

const completeJobTask = `-- name: CompleteJobTask :exec
UPDATE job_tasks
SET
  status = 'completed',
  error_message = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJobTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJobTask, id)
	return err
}

const failJobTask = `-- name: FailJobTask :exec
UPDATE job_tasks
SET
  status = 'failed',
  error_message = $2,
  updated_at = now()
WHERE id = $1
`

type FailJobTaskParams struct {
	ID           int64
	ErrorMessage *string
}

func (q *Queries) FailJobTask(ctx context.Context, arg FailJobTaskParams) error {
	_, err := q.db.Exec(ctx, failJobTask, arg.ID, arg.ErrorMessage)
	return err
}

const insertJobTask = `-- name: InsertJobTask :one
INSERT INTO job_tasks (job_id, rendition_id)
VALUES ($1, $2)
RETURNING id, job_id, rendition_id, status, error_message, created_at, updated_at
`

type InsertJobTaskParams struct {
	JobID       int64
	RenditionID int64
}

func (q *Queries) InsertJobTask(ctx context.Context, arg InsertJobTaskParams) (JobTask, error) {
	row := q.db.QueryRow(ctx, insertJobTask, arg.JobID, arg.RenditionID)
	var i JobTask
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RenditionID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobTaskStats = `-- name: JobTaskStats :one
SELECT
  COUNT(*) FILTER (WHERE status = 'pending')::bigint AS pending,
  COUNT(*) FILTER (WHERE status = 'running')::bigint AS running,
  COUNT(*) FILTER (WHERE status = 'completed')::bigint AS completed,
  COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed
FROM job_tasks
WHERE job_id = $1
`

type JobTaskStatsRow struct {
	Pending   int64
	Running   int64
	Completed int64
	Failed    int64
}

func (q *Queries) JobTaskStats(ctx context.Context, jobID int64) (JobTaskStatsRow, error) {
	row := q.db.QueryRow(ctx, jobTaskStats, jobID)
	var i JobTaskStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Running,
		&i.Completed,
		&i.Failed,
	)
	return i, err
}

const listJobRenditions = `-- name: ListJobRenditions :many
SELECT
  r.id,
  r.name,
  r.width,
  r.height,
  r.video_bitrate,
  r.audio_bitrate,
  r.video_codec,
  r.audio_codec,
  pr.stream_index
FROM job_tasks jt
JOIN jobs j ON j.id = jt.job_id
JOIN renditions r ON r.id = jt.rendition_id
LEFT JOIN profile_renditions pr
  ON pr.profile_id = j.profile_id AND pr.rendition_id = r.id
WHERE jt.job_id = $1
ORDER BY pr.stream_index NULLS LAST, r.name
`

type ListJobRenditionsRow struct {
	ID           int64
	Name         string
	Width        int32
	Height       int32
	VideoBitrate int32
	AudioBitrate int32
	VideoCodec   string
	AudioCodec   string
	StreamIndex  *int32
}

func (q *Queries) ListJobRenditions(ctx context.Context, jobID int64) ([]ListJobRenditionsRow, error) {
	rows, err := q.db.Query(ctx, listJobRenditions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobRenditionsRow
	for rows.Next() {
		var i ListJobRenditionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.VideoBitrate,
			&i.AudioBitrate,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.StreamIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE jobs
SET
  status = 'running',
  updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkJobRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markJobRunning, id)
	return err
}
