// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package queries

import (
	"context"
)

const claimJob = `-- name: ClaimJob :one
WITH next_job AS (
  SELECT id
  FROM jobs
  WHERE status = 'pending'
  ORDER BY created_at
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET
  status = 'running',
  updated_at = now()
FROM next_job
WHERE jobs.id = next_job.id
RETURNING jobs.id, jobs.source_path, jobs.output_dir, jobs.file_name, jobs.file_id, jobs.profile_id, jobs.status, jobs.progress_percent, jobs.error_message, jobs.retry_count, jobs.created_at, jobs.updated_at
`

func (q *Queries) ClaimJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.OutputDir,
		&i.FileName,
		&i.FileID,
		&i.ProfileID,
		&i.Status,
		&i.ProgressPercent,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET
  status = 'completed',
  progress_percent = 100,
  error_message = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (
  source_path,
  output_dir,
  file_name,
  file_id,
  profile_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, source_path, output_dir, file_name, file_id, profile_id, status, progress_percent, error_message, retry_count, created_at, updated_at
`

type EnqueueJobParams struct {
	SourcePath string
	OutputDir  string
	FileName   string
	FileID     *string
	ProfileID  int64
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.SourcePath,
		arg.OutputDir,
		arg.FileName,
		arg.FileID,
		arg.ProfileID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.OutputDir,
		&i.FileName,
		&i.FileID,
		&i.ProfileID,
		&i.Status,
		&i.ProgressPercent,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET
  status = 'failed',
  error_message = $2,
  retry_count = retry_count + 1,
  updated_at = now()
WHERE id = $1
`

type FailJobParams struct {
	ID           int64
	ErrorMessage *string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.ErrorMessage)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, source_path, output_dir, file_name, file_id, profile_id, status, progress_percent, error_message, retry_count, created_at, updated_at FROM jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.OutputDir,
		&i.FileName,
		&i.FileID,
		&i.ProfileID,
		&i.Status,
		&i.ProgressPercent,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs
SET
  progress_percent = $2,
  updated_at = now()
WHERE id = $1
`

type UpdateJobProgressParams struct {
	ID              int64
	ProgressPercent float32
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateJobProgress, arg.ID, arg.ProgressPercent)
	return err
}
