// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type ProfileRendition struct {
	ProfileID   sql.NullInt64
	RenditionID sql.NullInt64
	StreamIndex int64
}

type Rendition struct {
	ID           int64
	Name         string
	Width        int64
	Height       int64
	VideoBitrate int64
	AudioBitrate int64
	VideoCodec   sql.NullString
	AudioCodec   sql.NullString
	Fps          sql.NullInt64
	CreatedAt    interface{}
}

type TranscodeProfile struct {
	ID             int64
	Name           string
	Description    sql.NullString
	HlsSegmentTime sql.NullInt64
	IsDefault      sql.NullBool
	CreatedAt      interface{}
}
