// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID              int64
	SourcePath      string
	OutputDir       string
	FileName        string
	FileID          *string
	ProfileID       int64
	Status          string
	ProgressPercent float32
	ErrorMessage    *string
	RetryCount      int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JobTask struct {
	ID           int64
	JobID        int64
	RenditionID  int64
	Status       string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PendingFile struct {
	ID        int64
	FileName  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProfileRendition struct {
	ProfileID   int64
	RenditionID int64
	StreamIndex int32
}

type Rendition struct {
	ID           int64
	Name         string
	Width        int32
	Height       int32
	VideoBitrate int32
	AudioBitrate int32
	VideoCodec   string
	AudioCodec   string
	Fps          int32
	CreatedAt    pgtype.Timestamptz
}

type TranscodeProfile struct {
	ID             int64
	Name           string
	Description    *string
	HlsSegmentTime int32
	IsDefault      bool
	CreatedAt      pgtype.Timestamptz
}
