// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_files.sql

package queries

import (
	"context"
)

const createPendingFile = `-- name: CreatePendingFile :one
INSERT INTO pending_files (file_name) VALUES ($1) RETURNING id, file_name, status, created_at, updated_at
`

func (q *Queries) CreatePendingFile(ctx context.Context, fileName string) (PendingFile, error) {
	row := q.db.QueryRow(ctx, createPendingFile, fileName)
	var i PendingFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingFile = `-- name: GetPendingFile :one
SELECT id, file_name, status, created_at, updated_at FROM pending_files WHERE file_name = $1 AND status = 'waiting'
`

func (q *Queries) GetPendingFile(ctx context.Context, fileName string) (PendingFile, error) {
	row := q.db.QueryRow(ctx, getPendingFile, fileName)
	var i PendingFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingFiles = `-- name: GetPendingFiles :many
SELECT id, file_name, status, created_at, updated_at FROM pending_files WHERE status = 'waiting'
`

func (q *Queries) GetPendingFiles(ctx context.Context) ([]PendingFile, error) {
	rows, err := q.db.Query(ctx, getPendingFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingFile
	for rows.Next() {
		var i PendingFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePendingFileStatus = `-- name: UpdatePendingFileStatus :exec
UPDATE pending_files SET status = $2 WHERE id = $1
`

type UpdatePendingFileStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdatePendingFileStatus(ctx context.Context, arg UpdatePendingFileStatusParams) error {
	_, err := q.db.Exec(ctx, updatePendingFileStatus, arg.ID, arg.Status)
	return err
}
