// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_renditions.sql

package queries

import (
	"context"
)

const linkProfileRendition = `-- name: LinkProfileRendition :exec
INSERT INTO profile_renditions (profile_id, rendition_id, stream_index)
VALUES ($1, $2, $3)
`

type LinkProfileRenditionParams struct {
	ProfileID   int64
	RenditionID int64
	StreamIndex int32
}

func (q *Queries) LinkProfileRendition(ctx context.Context, arg LinkProfileRenditionParams) error {
	_, err := q.db.Exec(ctx, linkProfileRendition, arg.ProfileID, arg.RenditionID, arg.StreamIndex)
	return err
}
