// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: renditions.sql

package queries

import (
	"context"
	"database/sql"
)

const createRendition = `-- name: CreateRendition :one
INSERT INTO renditions(
  name,
  width,
  height,
  video_bitrate,
  audio_bitrate,
  video_codec,
  audio_codec,
  fps,
  created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, width, height, video_bitrate, audio_bitrate, video_codec, audio_codec, fps, created_at
`

type CreateRenditionParams struct {
	Name         string
	Width        int64
	Height       int64
	VideoBitrate int64
	AudioBitrate int64
	VideoCodec   sql.NullString
	AudioCodec   sql.NullString
	Fps          sql.NullInt64
	CreatedAt    interface{}
}

func (q *Queries) CreateRendition(ctx context.Context, arg CreateRenditionParams) (Rendition, error) {
	row := q.db.QueryRowContext(ctx, createRendition,
		arg.Name,
		arg.Width,
		arg.Height,
		arg.VideoBitrate,
		arg.AudioBitrate,
		arg.VideoCodec,
		arg.AudioCodec,
		arg.Fps,
		arg.CreatedAt,
	)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.VideoBitrate,
		&i.AudioBitrate,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Fps,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRendition = `-- name: DeleteRendition :exec
DELETE FROM renditions WHERE id = ?
`

func (q *Queries) DeleteRendition(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRendition, id)
	return err
}

const getRenditionById = `-- name: GetRenditionById :one
SELECT id, name, width, height, video_bitrate, audio_bitrate, video_codec, audio_codec, fps, created_at FROM renditions WHERE id = ? LIMIT 1
`

func (q *Queries) GetRenditionById(ctx context.Context, id int64) (Rendition, error) {
	row := q.db.QueryRowContext(ctx, getRenditionById, id)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.VideoBitrate,
		&i.AudioBitrate,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Fps,
		&i.CreatedAt,
	)
	return i, err
}

const getRenditionByName = `-- name: GetRenditionByName :one
SELECT id, name, width, height, video_bitrate, audio_bitrate, video_codec, audio_codec, fps, created_at FROM renditions WHERE name = ? LIMIT 1
`

func (q *Queries) GetRenditionByName(ctx context.Context, name string) (Rendition, error) {
	row := q.db.QueryRowContext(ctx, getRenditionByName, name)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.VideoBitrate,
		&i.AudioBitrate,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Fps,
		&i.CreatedAt,
	)
	return i, err
}
