// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcode_profiles.sql

package queries

import (
	"context"
	"database/sql"
)

const createTranscodeProfile = `-- name: CreateTranscodeProfile :one
INSERT INTO transcode_profiles(
  name,
  description,
  hls_segment_time,
  is_default,
  created_at
)
VALUES (?, ?, ?, ?, now())
RETURNING id, name, description, hls_segment_time, is_default, created_at
`

type CreateTranscodeProfileParams struct {
	Name           string
	Description    sql.NullString
	HlsSegmentTime sql.NullInt64
	IsDefault      sql.NullBool
}

func (q *Queries) CreateTranscodeProfile(ctx context.Context, arg CreateTranscodeProfileParams) (TranscodeProfile, error) {
	row := q.db.QueryRowContext(ctx, createTranscodeProfile,
		arg.Name,
		arg.Description,
		arg.HlsSegmentTime,
		arg.IsDefault,
	)
	var i TranscodeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.HlsSegmentTime,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileWithRenditions = `-- name: GetProfileWithRenditions :many
SELECT
  p.id AS profile_id,
  p.name AS profile_name,
  p.description AS profile_description,
  p.hls_segment_time,
  r.id AS rendition_id,
  r.name AS rendition_name,
  r.width,
  r.height,
  r.video_bitrate,
  r.audio_bitrate,
  r.video_codec,
  r.audio_codec,
  pr.stream_index
FROM transcode_profiles AS p
JOIN profile_renditions AS pr
  ON p.id = pr.profile_id
JOIN renditions AS r
  ON r.id = pr.rendition_id
WHERE
  p.id = ?
ORDER BY
  pr.stream_index
`

type GetProfileWithRenditionsRow struct {
	ProfileID          int64
	ProfileName        string
	ProfileDescription sql.NullString
	HlsSegmentTime     sql.NullInt64
	RenditionID        int64
	RenditionName      string
	Width              int64
	Height             int64
	VideoBitrate       int64
	AudioBitrate       int64
	VideoCodec         sql.NullString
	AudioCodec         sql.NullString
	StreamIndex        int64
}

func (q *Queries) GetProfileWithRenditions(ctx context.Context, id int64) ([]GetProfileWithRenditionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProfileWithRenditions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfileWithRenditionsRow
	for rows.Next() {
		var i GetProfileWithRenditionsRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.ProfileName,
			&i.ProfileDescription,
			&i.HlsSegmentTime,
			&i.RenditionID,
			&i.RenditionName,
			&i.Width,
			&i.Height,
			&i.VideoBitrate,
			&i.AudioBitrate,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.StreamIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranscodeProfileByName = `-- name: GetTranscodeProfileByName :one
SELECT id, name, description, hls_segment_time, is_default, created_at FROM transcode_profiles WHERE name = ? LIMIT 1
`

func (q *Queries) GetTranscodeProfileByName(ctx context.Context, name string) (TranscodeProfile, error) {
	row := q.db.QueryRowContext(ctx, getTranscodeProfileByName, name)
	var i TranscodeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.HlsSegmentTime,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
