syntax = "proto3";

package transcoder.v1;

option go_package = "github.com/crimsonn/media_pipeline/pkg/pb;pb";

enum TranscodeState {
  TRANSCODE_STATE_UNSPECIFIED = 0;
  TRANSCODE_STATE_IN_PROGRESS = 1;
  TRANSCODE_STATE_COMPLETED = 2;
  TRANSCODE_STATE_FAILED = 3;
}

service TranscoderService {
  rpc TranscodeVideo(TranscodeVideoRequest) returns (stream TranscodeVideoResponse);
}

message TranscodeResolution {
    string name = 1;
    int32 width = 2;
    int32 height = 3;
    int32 video_bps = 4;
    int32 audio_bps = 5;
}

message TranscodeVideoResponse {
  string task_id = 1;
  TranscodeState state = 2;
  int32 percent_complete = 3;
  string error_message = 5;
}

message TranscodeVideoRequest {
  string file_name = 1;
  string file_id = 2;
  string source_file_path = 3;
  string output_directory = 4;
  repeated TranscodeResolution resolutions = 5;
}
