/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardPendingRouteImport } from './routes/_dashboard/pending'
import { Route as DashboardPlaybackRouteImport } from './routes/_dashboard/playback'
import { Route as DashboardProfilesRouteImport } from './routes/_dashboard/profiles'
import { Route as DashboardRenditionsRouteImport } from './routes/_dashboard/renditions'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPendingRoute = DashboardPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaybackRoute = DashboardPlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfilesRoute = DashboardProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRenditionsRoute = DashboardRenditionsRouteImport.update({
  id: '/renditions',
  path: '/renditions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/pending': typeof DashboardPendingRoute
  '/playback': typeof DashboardPlaybackRoute
  '/profiles': typeof DashboardProfilesRoute
  '/renditions': typeof DashboardRenditionsRoute
}
export interface FileRoutesByTo {
  '/pending': typeof DashboardPendingRoute
  '/playback': typeof DashboardPlaybackRoute
  '/profiles': typeof DashboardProfilesRoute
  '/renditions': typeof DashboardRenditionsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/pending': typeof DashboardPendingRoute
  '/_dashboard/playback': typeof DashboardPlaybackRoute
  '/_dashboard/profiles': typeof DashboardProfilesRoute
  '/_dashboard/renditions': typeof DashboardRenditionsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pending' | '/playback' | '/profiles' | '/renditions'
  fileRoutesByTo: FileRoutesByTo
  to: '/pending' | '/playback' | '/profiles' | '/renditions' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/pending'
    | '/_dashboard/playback'
    | '/_dashboard/profiles'
    | '/_dashboard/renditions'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pending': {
      id: '/_dashboard/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof DashboardPendingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/playback': {
      id: '/_dashboard/playback'
      path: '/playback'
      fullPath: '/playback'
      preLoaderRoute: typeof DashboardPlaybackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profiles': {
      id: '/_dashboard/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof DashboardProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/renditions': {
      id: '/_dashboard/renditions'
      path: '/renditions'
      fullPath: '/renditions'
      preLoaderRoute: typeof DashboardRenditionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPendingRoute: typeof DashboardPendingRoute
  DashboardPlaybackRoute: typeof DashboardPlaybackRoute
  DashboardProfilesRoute: typeof DashboardProfilesRoute
  DashboardRenditionsRoute: typeof DashboardRenditionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPendingRoute: DashboardPendingRoute,
  DashboardPlaybackRoute: DashboardPlaybackRoute,
  DashboardProfilesRoute: DashboardProfilesRoute,
  DashboardRenditionsRoute: DashboardRenditionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
