// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: transcoder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscodeState int32

const (
	TranscodeState_STATE_PROCESSING TranscodeState = 0
	TranscodeState_STATE_COMPLETED  TranscodeState = 1
	TranscodeState_STATE_FAILED     TranscodeState = 3
)

// Enum value maps for TranscodeState.
var (
	TranscodeState_name = map[int32]string{
		0: "STATE_PROCESSING",
		1: "STATE_COMPLETED",
		3: "STATE_FAILED",
	}
	TranscodeState_value = map[string]int32{
		"STATE_PROCESSING": 0,
		"STATE_COMPLETED":  1,
		"STATE_FAILED":     3,
	}
)

func (x TranscodeState) Enum() *TranscodeState {
	p := new(TranscodeState)
	*p = x
	return p
}

func (x TranscodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_transcoder_proto_enumTypes[0].Descriptor()
}

func (TranscodeState) Type() protoreflect.EnumType {
	return &file_transcoder_proto_enumTypes[0]
}

func (x TranscodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscodeState.Descriptor instead.
func (TranscodeState) EnumDescriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{0}
}

type TranscodeProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State           TranscodeState         `protobuf:"varint,2,opt,name=state,proto3,enum=transcoder.v1.TranscodeState" json:"state,omitempty"`
	PercentComplete int32                  `protobuf:"varint,3,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranscodeProgress) Reset() {
	*x = TranscodeProgress{}
	mi := &file_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeProgress) ProtoMessage() {}

func (x *TranscodeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeProgress.ProtoReflect.Descriptor instead.
func (*TranscodeProgress) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *TranscodeProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TranscodeProgress) GetState() TranscodeState {
	if x != nil {
		return x.State
	}
	return TranscodeState_STATE_PROCESSING
}

func (x *TranscodeProgress) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *TranscodeProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TranscodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FileId            string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SourceFilePath    string                 `protobuf:"bytes,2,opt,name=source_file_path,json=sourceFilePath,proto3" json:"source_file_path,omitempty"`
	OutputDirectory   string                 `protobuf:"bytes,3,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	TargetResolutions []string               `protobuf:"bytes,4,rep,name=target_resolutions,json=targetResolutions,proto3" json:"target_resolutions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TranscodeRequest) Reset() {
	*x = TranscodeRequest{}
	mi := &file_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequest) ProtoMessage() {}

func (x *TranscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequest.ProtoReflect.Descriptor instead.
func (*TranscodeRequest) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{1}
}

func (x *TranscodeRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *TranscodeRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

func (x *TranscodeRequest) GetOutputDirectory() string {
	if x != nil {
		return x.OutputDirectory
	}
	return ""
}

func (x *TranscodeRequest) GetTargetResolutions() []string {
	if x != nil {
		return x.TargetResolutions
	}
	return nil
}

var File_transcoder_proto protoreflect.FileDescriptor

const file_transcoder_proto_rawDesc = "" +
	"\n" +
	"\x10transcoder.proto\x12\rtranscoder.v1\"\xb1\x01\n" +
	"\x11TranscodeProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.transcoder.v1.TranscodeStateR\x05state\x12)\n" +
	"\x10percent_complete\x18\x03 \x01(\x05R\x0fpercentComplete\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xaf\x01\n" +
	"\x10TranscodeRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12(\n" +
	"\x10source_file_path\x18\x02 \x01(\tR\x0esourceFilePath\x12)\n" +
	"\x10output_directory\x18\x03 \x01(\tR\x0foutputDirectory\x12-\n" +
	"\x12target_resolutions\x18\x04 \x03(\tR\x11targetResolutions*M\n" +
	"\x0eTranscodeState\x12\x14\n" +
	"\x10STATE_PROCESSING\x10\x00\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x032j\n" +
	"\x11TranscoderService\x12U\n" +
	"\x0eTranscodeVideo\x12\x1f.transcoder.v1.TranscodeRequest\x1a .transcoder.v1.TranscodeProgress0\x01B.Z,github.com/crimsonn/media_pipeline/pkg/pb;pbb\x06proto3"

var (
	file_transcoder_proto_rawDescOnce sync.Once
	file_transcoder_proto_rawDescData []byte
)

func file_transcoder_proto_rawDescGZIP() []byte {
	file_transcoder_proto_rawDescOnce.Do(func() {
		file_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)))
	})
	return file_transcoder_proto_rawDescData
}

var file_transcoder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transcoder_proto_goTypes = []any{
	(TranscodeState)(0),       // 0: transcoder.v1.TranscodeState
	(*TranscodeProgress)(nil), // 1: transcoder.v1.TranscodeProgress
	(*TranscodeRequest)(nil),  // 2: transcoder.v1.TranscodeRequest
}
var file_transcoder_proto_depIdxs = []int32{
	0, // 0: transcoder.v1.TranscodeProgress.state:type_name -> transcoder.v1.TranscodeState
	2, // 1: transcoder.v1.TranscoderService.TranscodeVideo:input_type -> transcoder.v1.TranscodeRequest
	1, // 2: transcoder.v1.TranscoderService.TranscodeVideo:output_type -> transcoder.v1.TranscodeProgress
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transcoder_proto_init() }
func file_transcoder_proto_init() {
	if File_transcoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoder_proto_goTypes,
		DependencyIndexes: file_transcoder_proto_depIdxs,
		EnumInfos:         file_transcoder_proto_enumTypes,
		MessageInfos:      file_transcoder_proto_msgTypes,
	}.Build()
	File_transcoder_proto = out.File
	file_transcoder_proto_goTypes = nil
	file_transcoder_proto_depIdxs = nil
}
