// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: transcoder/v1/transcoder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscodeState int32

const (
	TranscodeState_TRANSCODE_STATE_UNSPECIFIED TranscodeState = 0
	TranscodeState_TRANSCODE_STATE_IN_PROGRESS TranscodeState = 1
	TranscodeState_TRANSCODE_STATE_COMPLETED   TranscodeState = 2
	TranscodeState_TRANSCODE_STATE_FAILED      TranscodeState = 3
)

// Enum value maps for TranscodeState.
var (
	TranscodeState_name = map[int32]string{
		0: "TRANSCODE_STATE_UNSPECIFIED",
		1: "TRANSCODE_STATE_IN_PROGRESS",
		2: "TRANSCODE_STATE_COMPLETED",
		3: "TRANSCODE_STATE_FAILED",
	}
	TranscodeState_value = map[string]int32{
		"TRANSCODE_STATE_UNSPECIFIED": 0,
		"TRANSCODE_STATE_IN_PROGRESS": 1,
		"TRANSCODE_STATE_COMPLETED":   2,
		"TRANSCODE_STATE_FAILED":      3,
	}
)

func (x TranscodeState) Enum() *TranscodeState {
	p := new(TranscodeState)
	*p = x
	return p
}

func (x TranscodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_transcoder_v1_transcoder_proto_enumTypes[0].Descriptor()
}

func (TranscodeState) Type() protoreflect.EnumType {
	return &file_transcoder_v1_transcoder_proto_enumTypes[0]
}

func (x TranscodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscodeState.Descriptor instead.
func (TranscodeState) EnumDescriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{0}
}

type TranscodeResolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	VideoBps      int32                  `protobuf:"varint,4,opt,name=video_bps,json=videoBps,proto3" json:"video_bps,omitempty"`
	AudioBps      int32                  `protobuf:"varint,5,opt,name=audio_bps,json=audioBps,proto3" json:"audio_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeResolution) Reset() {
	*x = TranscodeResolution{}
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeResolution) ProtoMessage() {}

func (x *TranscodeResolution) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeResolution.ProtoReflect.Descriptor instead.
func (*TranscodeResolution) Descriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *TranscodeResolution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranscodeResolution) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TranscodeResolution) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TranscodeResolution) GetVideoBps() int32 {
	if x != nil {
		return x.VideoBps
	}
	return 0
}

func (x *TranscodeResolution) GetAudioBps() int32 {
	if x != nil {
		return x.AudioBps
	}
	return 0
}

type TranscodeVideoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State           TranscodeState         `protobuf:"varint,2,opt,name=state,proto3,enum=transcoder.v1.TranscodeState" json:"state,omitempty"`
	PercentComplete int32                  `protobuf:"varint,3,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranscodeVideoResponse) Reset() {
	*x = TranscodeVideoResponse{}
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeVideoResponse) ProtoMessage() {}

func (x *TranscodeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeVideoResponse.ProtoReflect.Descriptor instead.
func (*TranscodeVideoResponse) Descriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{1}
}

func (x *TranscodeVideoResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TranscodeVideoResponse) GetState() TranscodeState {
	if x != nil {
		return x.State
	}
	return TranscodeState_TRANSCODE_STATE_UNSPECIFIED
}

func (x *TranscodeVideoResponse) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *TranscodeVideoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TranscodeVideoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileName        string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileId          string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SourceFilePath  string                 `protobuf:"bytes,3,opt,name=source_file_path,json=sourceFilePath,proto3" json:"source_file_path,omitempty"`
	OutputDirectory string                 `protobuf:"bytes,4,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	Resolutions     []*TranscodeResolution `protobuf:"bytes,5,rep,name=resolutions,proto3" json:"resolutions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranscodeVideoRequest) Reset() {
	*x = TranscodeVideoRequest{}
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeVideoRequest) ProtoMessage() {}

func (x *TranscodeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_v1_transcoder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeVideoRequest.ProtoReflect.Descriptor instead.
func (*TranscodeVideoRequest) Descriptor() ([]byte, []int) {
	return file_transcoder_v1_transcoder_proto_rawDescGZIP(), []int{2}
}

func (x *TranscodeVideoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TranscodeVideoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *TranscodeVideoRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

func (x *TranscodeVideoRequest) GetOutputDirectory() string {
	if x != nil {
		return x.OutputDirectory
	}
	return ""
}

func (x *TranscodeVideoRequest) GetResolutions() []*TranscodeResolution {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

var File_transcoder_v1_transcoder_proto protoreflect.FileDescriptor

const file_transcoder_v1_transcoder_proto_rawDesc = "" +
	"\n" +
	"\x1etranscoder/v1/transcoder.proto\x12\rtranscoder.v1\"\x91\x01\n" +
	"\x13TranscodeResolution\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1b\n" +
	"\tvideo_bps\x18\x04 \x01(\x05R\bvideoBps\x12\x1b\n" +
	"\taudio_bps\x18\x05 \x01(\x05R\baudioBps\"\xb6\x01\n" +
	"\x16TranscodeVideoResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.transcoder.v1.TranscodeStateR\x05state\x12)\n" +
	"\x10percent_complete\x18\x03 \x01(\x05R\x0fpercentComplete\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xe8\x01\n" +
	"\x15TranscodeVideoRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12(\n" +
	"\x10source_file_path\x18\x03 \x01(\tR\x0esourceFilePath\x12)\n" +
	"\x10output_directory\x18\x04 \x01(\tR\x0foutputDirectory\x12D\n" +
	"\vresolutions\x18\x05 \x03(\v2\".transcoder.v1.TranscodeResolutionR\vresolutions*\x8d\x01\n" +
	"\x0eTranscodeState\x12\x1f\n" +
	"\x1bTRANSCODE_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRANSCODE_STATE_IN_PROGRESS\x10\x01\x12\x1d\n" +
	"\x19TRANSCODE_STATE_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16TRANSCODE_STATE_FAILED\x10\x032t\n" +
	"\x11TranscoderService\x12_\n" +
	"\x0eTranscodeVideo\x12$.transcoder.v1.TranscodeVideoRequest\x1a%.transcoder.v1.TranscodeVideoResponse0\x01B.Z,github.com/crimsonn/media_pipeline/pkg/pb;pbb\x06proto3"

var (
	file_transcoder_v1_transcoder_proto_rawDescOnce sync.Once
	file_transcoder_v1_transcoder_proto_rawDescData []byte
)

func file_transcoder_v1_transcoder_proto_rawDescGZIP() []byte {
	file_transcoder_v1_transcoder_proto_rawDescOnce.Do(func() {
		file_transcoder_v1_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoder_v1_transcoder_proto_rawDesc), len(file_transcoder_v1_transcoder_proto_rawDesc)))
	})
	return file_transcoder_v1_transcoder_proto_rawDescData
}

var file_transcoder_v1_transcoder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transcoder_v1_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transcoder_v1_transcoder_proto_goTypes = []any{
	(TranscodeState)(0),            // 0: transcoder.v1.TranscodeState
	(*TranscodeResolution)(nil),    // 1: transcoder.v1.TranscodeResolution
	(*TranscodeVideoResponse)(nil), // 2: transcoder.v1.TranscodeVideoResponse
	(*TranscodeVideoRequest)(nil),  // 3: transcoder.v1.TranscodeVideoRequest
}
var file_transcoder_v1_transcoder_proto_depIdxs = []int32{
	0, // 0: transcoder.v1.TranscodeVideoResponse.state:type_name -> transcoder.v1.TranscodeState
	1, // 1: transcoder.v1.TranscodeVideoRequest.resolutions:type_name -> transcoder.v1.TranscodeResolution
	3, // 2: transcoder.v1.TranscoderService.TranscodeVideo:input_type -> transcoder.v1.TranscodeVideoRequest
	2, // 3: transcoder.v1.TranscoderService.TranscodeVideo:output_type -> transcoder.v1.TranscodeVideoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transcoder_v1_transcoder_proto_init() }
func file_transcoder_v1_transcoder_proto_init() {
	if File_transcoder_v1_transcoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoder_v1_transcoder_proto_rawDesc), len(file_transcoder_v1_transcoder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoder_v1_transcoder_proto_goTypes,
		DependencyIndexes: file_transcoder_v1_transcoder_proto_depIdxs,
		EnumInfos:         file_transcoder_v1_transcoder_proto_enumTypes,
		MessageInfos:      file_transcoder_v1_transcoder_proto_msgTypes,
	}.Build()
	File_transcoder_v1_transcoder_proto = out.File
	file_transcoder_v1_transcoder_proto_goTypes = nil
	file_transcoder_v1_transcoder_proto_depIdxs = nil
}
