// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: transcoder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FileId            string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SourceFilePath    string                 `protobuf:"bytes,2,opt,name=source_file_path,json=sourceFilePath,proto3" json:"source_file_path,omitempty"`
	OutputDirectory   string                 `protobuf:"bytes,3,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	TargetResolutions []string               `protobuf:"bytes,4,rep,name=target_resolutions,json=targetResolutions,proto3" json:"target_resolutions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TranscodeRequest) Reset() {
	*x = TranscodeRequest{}
	mi := &file_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequest) ProtoMessage() {}

func (x *TranscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequest.ProtoReflect.Descriptor instead.
func (*TranscodeRequest) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *TranscodeRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *TranscodeRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

func (x *TranscodeRequest) GetOutputDirectory() string {
	if x != nil {
		return x.OutputDirectory
	}
	return ""
}

func (x *TranscodeRequest) GetTargetResolutions() []string {
	if x != nil {
		return x.TargetResolutions
	}
	return nil
}

type TranscodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FileId            string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MasterPlaylistUrl string                 `protobuf:"bytes,3,opt,name=master_playlist_url,json=masterPlaylistUrl,proto3" json:"master_playlist_url,omitempty"`
	DurationSeconds   float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TranscodeResponse) Reset() {
	*x = TranscodeResponse{}
	mi := &file_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeResponse) ProtoMessage() {}

func (x *TranscodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeResponse.ProtoReflect.Descriptor instead.
func (*TranscodeResponse) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{1}
}

func (x *TranscodeResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *TranscodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TranscodeResponse) GetMasterPlaylistUrl() string {
	if x != nil {
		return x.MasterPlaylistUrl
	}
	return ""
}

func (x *TranscodeResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TranscodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_transcoder_proto protoreflect.FileDescriptor

const file_transcoder_proto_rawDesc = "" +
	"\n" +
	"\x10transcoder.proto\x12\rtranscoder.v1\"\xaf\x01\n" +
	"\x10TranscodeRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12(\n" +
	"\x10source_file_path\x18\x02 \x01(\tR\x0esourceFilePath\x12)\n" +
	"\x10output_directory\x18\x03 \x01(\tR\x0foutputDirectory\x12-\n" +
	"\x12target_resolutions\x18\x04 \x03(\tR\x11targetResolutions\"\xc6\x01\n" +
	"\x11TranscodeResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12.\n" +
	"\x13master_playlist_url\x18\x03 \x01(\tR\x11masterPlaylistUrl\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage2h\n" +
	"\x11TranscoderService\x12S\n" +
	"\x0eTranscodeVideo\x12\x1f.transcoder.v1.TranscodeRequest\x1a .transcoder.v1.TranscodeResponseB.Z,github.com/crimsonn/media_pipeline/pkg/pb;pbb\x06proto3"

var (
	file_transcoder_proto_rawDescOnce sync.Once
	file_transcoder_proto_rawDescData []byte
)

func file_transcoder_proto_rawDescGZIP() []byte {
	file_transcoder_proto_rawDescOnce.Do(func() {
		file_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)))
	})
	return file_transcoder_proto_rawDescData
}

var file_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transcoder_proto_goTypes = []any{
	(*TranscodeRequest)(nil),  // 0: transcoder.v1.TranscodeRequest
	(*TranscodeResponse)(nil), // 1: transcoder.v1.TranscodeResponse
}
var file_transcoder_proto_depIdxs = []int32{
	0, // 0: transcoder.v1.TranscoderService.TranscodeVideo:input_type -> transcoder.v1.TranscodeRequest
	1, // 1: transcoder.v1.TranscoderService.TranscodeVideo:output_type -> transcoder.v1.TranscodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transcoder_proto_init() }
func file_transcoder_proto_init() {
	if File_transcoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoder_proto_goTypes,
		DependencyIndexes: file_transcoder_proto_depIdxs,
		MessageInfos:      file_transcoder_proto_msgTypes,
	}.Build()
	File_transcoder_proto = out.File
	file_transcoder_proto_goTypes = nil
	file_transcoder_proto_depIdxs = nil
}
