// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: transcoder.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscoderService_TranscodeVideo_FullMethodName = "/transcoder.v1.TranscoderService/TranscodeVideo"
)

// TranscoderServiceClient is the client API for TranscoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscoderServiceClient interface {
	TranscodeVideo(ctx context.Context, in *TranscodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranscodeProgress], error)
}

type transcoderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscoderServiceClient(cc grpc.ClientConnInterface) TranscoderServiceClient {
	return &transcoderServiceClient{cc}
}

func (c *transcoderServiceClient) TranscodeVideo(ctx context.Context, in *TranscodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranscodeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranscoderService_ServiceDesc.Streams[0], TranscoderService_TranscodeVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscodeRequest, TranscodeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranscoderService_TranscodeVideoClient = grpc.ServerStreamingClient[TranscodeProgress]

// TranscoderServiceServer is the server API for TranscoderService service.
// All implementations must embed UnimplementedTranscoderServiceServer
// for forward compatibility.
type TranscoderServiceServer interface {
	TranscodeVideo(*TranscodeRequest, grpc.ServerStreamingServer[TranscodeProgress]) error
	mustEmbedUnimplementedTranscoderServiceServer()
}

// UnimplementedTranscoderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscoderServiceServer struct{}

func (UnimplementedTranscoderServiceServer) TranscodeVideo(*TranscodeRequest, grpc.ServerStreamingServer[TranscodeProgress]) error {
	return status.Error(codes.Unimplemented, "method TranscodeVideo not implemented")
}
func (UnimplementedTranscoderServiceServer) mustEmbedUnimplementedTranscoderServiceServer() {}
func (UnimplementedTranscoderServiceServer) testEmbeddedByValue()                           {}

// UnsafeTranscoderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscoderServiceServer will
// result in compilation errors.
type UnsafeTranscoderServiceServer interface {
	mustEmbedUnimplementedTranscoderServiceServer()
}

func RegisterTranscoderServiceServer(s grpc.ServiceRegistrar, srv TranscoderServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscoderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscoderService_ServiceDesc, srv)
}

func _TranscoderService_TranscodeVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranscodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TranscoderServiceServer).TranscodeVideo(m, &grpc.GenericServerStream[TranscodeRequest, TranscodeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranscoderService_TranscodeVideoServer = grpc.ServerStreamingServer[TranscodeProgress]

// TranscoderService_ServiceDesc is the grpc.ServiceDesc for TranscoderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscoderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcoder.v1.TranscoderService",
	HandlerType: (*TranscoderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranscodeVideo",
			Handler:       _TranscoderService_TranscodeVideo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transcoder.proto",
}
